language: generic 
sudo: required
services :
  - docker

before install:
  - docker build -t dakshbhardwaj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dakshbhardwaj/docker-react npm run test -- --coverage

deploy :
  provider : elasticbeanstalk
  region : "ap-south-1"
  app : "docker-react"
  env : "DockerReact-env"
  bucket_name : "elasticbeanstalk-ap-south-1-484195276275"
  bucket_path : "docker-react"
  on :
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : 
    secure : "$AWS_SECRET_KEY"

